name: Java CI

on:
  push:
    paths:
      - 'java/**'
  pull_request:
    paths:
      - 'java/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run unit tests
        run: |
          cd java
          mvn clean verify
          cd target
          ls
      
      - name: Cahce Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=my-organization
            -Dsonar.projectKey=my-projectkey



  build:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      language: 'java'
