name: Node.js CI

on:
  push:
    paths:
      - 'nodejs/**'
  pull_request:
    paths:
      - 'nodejs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          cd nodejs
          npm install

      - name: Run unit tests
        run: |
          cd nodejs
          npm test

  sonar:
    needs: [test, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          projectBaseDir: nodejs
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



  build:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      language: 'node'
