name: Node.js CI

on:
  push:
    paths:
      - 'nodejs/**'
  pull_request:
    paths:
      - 'nodejs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          cd node
          npm install

      - name: Run unit tests
        run: |
          cd node
          npm test

  build:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      language: 'node'
